site_name: 清音为羽
site_url: https://chingjyu.cyou
repo_url: https://github.com/cv2wx/cv2wx.github.io
repo_name: cv2wx/cv2wx.github.io
copyright: Copyright &copy; 2023 Victor "the Ray"(清羽)

theme:
  name: material
  logo: 
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      toggle:
        icon: material/brightness-7

    - media: "(orefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4

markdown_extensions:
  - pymdownx.magiclink
  - admonition
  - pymdownx.details
  - pymdownx.superfences
nav:
  - 首页: index.md
  - 隐私政策: privacy_policy.md
