name: Publish site
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: mkdocs build
      - run: echo "chingjyu.cyou" > site/CNAME
      - run: mkdocs gh-deploy -m "{sha}" --ignore-version --dirty || true
      - run: cd site
      - run: git fetch origin gh-pages
      - run: git push origin gh-pages --force
