name: Publish site
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: |
             pip install mkdocs-material
             mkdocs build
             echo "chingjyu.cyou" > site/CNAME
             mkdocs gh-deploy -m "{sha}" --ignore-version --dirty || true
             cd site
             git fetch origin gh-pages
             git push origin gh-pages --force
